openapi: 3.0.6
info:
  title: Bookstore API
  version: 0.1.0
  description: REST API for managing a bookstore

servers:
  - url: http://localhost:8080

paths:
  /books:
    get:
      summary: List all books
      responses:
        '200':
          description: list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        price:
          type: string
          x-go-type: "decimal.Decimal"
        published_date:
          type: string
        stock:
          type: integer
